version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
        test: ['CMD-SHELL', 'mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}']
        interval: 1s
        timeout: 1s
        retries: 15

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: dev
    restart: always
    tty: true
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
        - .:/app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
